// =============================================
// MOCK DATA — mirrors Supabase schema exactly
// =============================================

export const PARTICLE_PRODUCTIONS = [
  {
    id: "PRD26-01",
    project_name: "Particle BrandFormance AI Campaign",
    product_type: ["Brandformance"],
    production_type: "AI",
    producer: "Omer Barak",
    planned_start: "2026-01-01",
    planned_end: "2026-01-31",
    planned_budget_2026: 1500,
    estimated_budget: 1500,
    actual_spent: 1500,
    payment_date: "2026-01-31",
    stage: "Completed",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-02",
    project_name: "Particle 43 Shaving Gel AI Campaign",
    product_type: ["Shaving Gel"],
    production_type: "AI",
    producer: "Omer Barak",
    planned_start: "2026-01-01",
    planned_end: "2026-01-31",
    planned_budget_2026: 1500,
    estimated_budget: 1500,
    actual_spent: 1500,
    payment_date: "2026-01-31",
    stage: "Completed",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-03",
    project_name: "Particle Anti-Gray Serum AI Campaign",
    product_type: ["Anti-Gray Serum"],
    production_type: "AI",
    producer: "Omer Barak",
    planned_start: "2026-02-01",
    planned_end: "2026-02-28",
    planned_budget_2026: 1500,
    estimated_budget: 1500,
    actual_spent: 1200,
    payment_date: "2026-02-28",
    stage: "Completed",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-05",
    project_name: "Particle Hand Cream AI Campaign",
    product_type: ["Hand Cream"],
    production_type: "AI",
    producer: "Omer Barak",
    planned_start: "2026-02-01",
    planned_end: "2026-02-28",
    planned_budget_2026: 1500,
    estimated_budget: 1500,
    actual_spent: 1400,
    payment_date: "2026-02-28",
    stage: "Completed",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-06",
    project_name: "Particle Face Cream Couple Testimonials March",
    product_type: ["Face Cream"],
    production_type: "Shoot",
    producer: "Omer Barak",
    planned_start: "2026-03-01",
    planned_end: "2026-03-31",
    planned_budget_2026: 10000,
    estimated_budget: 10000,
    actual_spent: 4200,
    payment_date: null,
    stage: "Production",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-07",
    project_name: "Particle AI NeoRoot Hair Renewal System",
    product_type: ["Neoroot"],
    production_type: "AI",
    producer: "Omer Barak",
    planned_start: "2026-04-01",
    planned_end: "2026-04-30",
    planned_budget_2026: 1500,
    estimated_budget: 1500,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-08",
    project_name: "Particle Face Cream Performance with Michael",
    product_type: ["Face Cream"],
    production_type: "Shoot",
    producer: "Omer Barak",
    planned_start: "2026-04-01",
    planned_end: "2026-04-30",
    planned_budget_2026: 25000,
    estimated_budget: 25000,
    actual_spent: 8000,
    payment_date: null,
    stage: "Production",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-09",
    project_name: "Particle Gravité Full Production Campaign",
    product_type: ["Gravité"],
    production_type: "Shoot",
    producer: "Omer Barak",
    planned_start: "2026-05-01",
    planned_end: "2026-05-31",
    planned_budget_2026: 50000,
    estimated_budget: 50000,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-10",
    project_name: "Particle Gravité Backup Testimonials May",
    product_type: ["Gravité"],
    production_type: "Remote Shoot",
    producer: "Omer Barak",
    planned_start: "2026-05-01",
    planned_end: "2026-05-31",
    planned_budget_2026: 20000,
    estimated_budget: 20000,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-11",
    project_name: "Particle Face Cream July Campaign",
    product_type: ["Face Cream"],
    production_type: "Shoot",
    producer: "Omer Barak",
    planned_start: "2026-07-01",
    planned_end: "2026-07-31",
    planned_budget_2026: 45000,
    estimated_budget: 45000,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-12",
    project_name: "Particle AI Saved Spot August Campaign",
    product_type: [],
    production_type: "AI",
    producer: "Omer Barak",
    planned_start: "2026-08-01",
    planned_end: "2026-08-31",
    planned_budget_2026: 1500,
    estimated_budget: 1500,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-13",
    project_name: "Particle July Main Campaign — TBD",
    product_type: [],
    production_type: "Shoot",
    producer: "Omer Barak",
    planned_start: "2026-07-01",
    planned_end: "2026-07-31",
    planned_budget_2026: 45000,
    estimated_budget: 45000,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-14",
    project_name: "Particle Gravité June Main Production",
    product_type: ["Gravité"],
    production_type: "Shoot",
    producer: "Omer Barak",
    planned_start: "2026-06-01",
    planned_end: "2026-06-30",
    planned_budget_2026: 55000,
    estimated_budget: 55000,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-15",
    project_name: "Particle Gravité June Testimonials",
    product_type: ["Gravité"],
    production_type: "Remote Shoot",
    producer: "Omer Barak",
    planned_start: "2026-06-01",
    planned_end: "2026-06-30",
    planned_budget_2026: 33500,
    estimated_budget: 33500,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-16",
    project_name: "Particle Face Cream September Main",
    product_type: ["Face Cream"],
    production_type: "Shoot",
    producer: "Omer Barak",
    planned_start: "2026-09-01",
    planned_end: "2026-09-30",
    planned_budget_2026: 45000,
    estimated_budget: 45000,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-17",
    project_name: "Particle AI Sports Invisible Sunscreen™",
    product_type: ["Sunscreen"],
    production_type: "AI",
    producer: "Omer Barak",
    planned_start: "2026-03-01",
    planned_end: "2026-03-31",
    planned_budget_2026: 1500,
    estimated_budget: 1500,
    actual_spent: 900,
    payment_date: null,
    stage: "Production",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-18",
    project_name: "Particle Face Cream Testimonials October",
    product_type: ["Face Cream"],
    production_type: "Shoot",
    producer: "Omer Barak",
    planned_start: "2026-10-01",
    planned_end: "2026-10-31",
    planned_budget_2026: 20000,
    estimated_budget: 20000,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-19",
    project_name: "Particle Campaign Saved Spot October",
    product_type: [],
    production_type: "Shoot",
    producer: "Omer Barak",
    planned_start: "2026-10-01",
    planned_end: "2026-10-31",
    planned_budget_2026: 45000,
    estimated_budget: 45000,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-20",
    project_name: "Particle Saved Spot",
    product_type: ["Face Cream"],
    production_type: "Shoot",
    producer: "Omer Barak",
    planned_start: "2026-08-01",
    planned_end: "2026-08-31",
    planned_budget_2026: 33000,
    estimated_budget: 33000,
    actual_spent: 0,
    payment_date: null,
    stage: "Pending",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-21",
    project_name: "Particle Flex Bank",
    product_type: [],
    production_type: "Shoot",
    producer: "Omer Barak",
    planned_start: "2026-01-01",
    planned_end: "2026-12-31",
    planned_budget_2026: 118000,
    estimated_budget: 118000,
    actual_spent: 22000,
    payment_date: null,
    stage: "Production",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-22",
    project_name: "Particle FC SilverFox AI",
    product_type: ["Face Cream"],
    production_type: "AI",
    producer: "Omer Barak",
    planned_start: "2026-02-01",
    planned_end: "2026-02-28",
    planned_budget_2026: 5000,
    estimated_budget: 5000,
    actual_spent: 0,
    payment_date: null,
    stage: "Pre Production",
    brand_id: "particle",
    production_year: 2026,
  },
  {
    id: "PRD26-23",
    project_name: "Gravite AI",
    product_type: ["Gravité"],
    production_type: "AI",
    producer: "Omer Barak",
    planned_start: "2026-02-01",
    planned_end: "2026-02-28",
    planned_budget_2026: 5000,
    estimated_budget: 5000,
    actual_spent: 5000,
    payment_date: "2026-02-28",
    stage: "Completed",
    brand_id: "particle",
    production_year: 2026,
  },
];

export const SAMPLE_LINE_ITEMS = {
  "PRD26-06": [
    { id: "li-001", production_id: "PRD26-06", item: "Director", full_name: "David Cohen", planned_budget: 3000, type: "Crew", status: "Done", timeline_start: "2026-03-05", timeline_end: "2026-03-10", actual_spent: 3000, payment_status: "Paid", payment_method: "Bank Transfer", payment_due: "2026-03-15", invoice_type: "tax_invoice_receipt", invoice_stage: "complete", invoice_status: "Received", notes: "", dealer_type: "osek_murshe" },
    { id: "li-002", production_id: "PRD26-06", item: "Talent", full_name: "Sarah & Michael", planned_budget: 2000, type: "Crew", status: "Done", timeline_start: "2026-03-08", timeline_end: "2026-03-10", actual_spent: 1800, payment_status: "Paid", payment_method: "Bit", payment_due: "2026-03-12", invoice_type: "receipt", invoice_stage: "complete", invoice_status: "Received", notes: "2 shoot days", dealer_type: "osek_patur" },
    { id: "li-003", production_id: "PRD26-06", item: "Camera Equipment", full_name: "Studio Pro Rentals", planned_budget: 1500, type: "Equipment", status: "Working on it", timeline_start: "2026-03-08", timeline_end: "2026-03-10", actual_spent: 0, payment_status: "Not Paid", payment_method: "", payment_due: "2026-04-01", invoice_type: null, invoice_stage: "pending", invoice_status: "", notes: "", dealer_type: "osek_murshe" },
    { id: "li-004", production_id: "PRD26-06", item: "Post Production", full_name: "Edit House TLV", planned_budget: 2500, type: "Post", status: "Not Started", timeline_start: "2026-03-15", timeline_end: "2026-03-25", actual_spent: 0, payment_status: "Not Paid", payment_method: "", payment_due: "2026-04-10", invoice_type: null, invoice_stage: "pending", invoice_status: "", notes: "Include color grading", dealer_type: "ltd" },
    { id: "li-005", production_id: "PRD26-06", item: "Catering", full_name: "Taste Events", planned_budget: 500, type: "Catering & Transport", status: "Done", timeline_start: "2026-03-08", timeline_end: "2026-03-10", actual_spent: 420, payment_status: "Paid", payment_method: "Credit Card", payment_due: "2026-03-10", invoice_type: "receipt", invoice_stage: "complete", invoice_status: "Received", notes: "", dealer_type: "osek_patur" },
  ],
  "PRD26-08": [
    { id: "li-010", production_id: "PRD26-08", item: "Director", full_name: "Amit Levi", planned_budget: 8000, type: "Crew", status: "Working on it", timeline_start: "2026-04-05", timeline_end: "2026-04-12", actual_spent: 4000, payment_status: "Pending", payment_method: "Bank Transfer", payment_due: "2026-04-20", invoice_type: "tax_invoice", invoice_stage: "tax_invoice_sent", invoice_status: "Received", notes: "50% advance paid", dealer_type: "osek_murshe" },
    { id: "li-011", production_id: "PRD26-08", item: "Actor — Michael", full_name: "Michael Friedman", planned_budget: 5000, type: "Crew", status: "Working on it", timeline_start: "2026-04-10", timeline_end: "2026-04-12", actual_spent: 2500, payment_status: "Pending", payment_method: "Bit", payment_due: "2026-04-15", invoice_type: "receipt", invoice_stage: "pending", invoice_status: "", notes: "", dealer_type: "osek_patur" },
    { id: "li-012", production_id: "PRD26-08", item: "Production Equipment", full_name: "FilmGear Israel", planned_budget: 4500, type: "Equipment", status: "Not Started", timeline_start: "2026-04-10", timeline_end: "2026-04-12", actual_spent: 0, payment_status: "Not Paid", payment_method: "", payment_due: "2026-05-01", invoice_type: null, invoice_stage: "pending", invoice_status: "", notes: "", dealer_type: "osek_murshe" },
    { id: "li-013", production_id: "PRD26-08", item: "Post Production", full_name: "Post Perfect TLV", planned_budget: 6000, type: "Post", status: "Not Started", timeline_start: "2026-04-15", timeline_end: "2026-04-30", actual_spent: 0, payment_status: "Not Paid", payment_method: "", payment_due: "2026-05-15", invoice_type: null, invoice_stage: "pending", invoice_status: "", notes: "", dealer_type: "ltd" },
    { id: "li-014", production_id: "PRD26-08", item: "Transport & Catering", full_name: "Logistics Plus", planned_budget: 1500, type: "Catering & Transport", status: "Not Started", timeline_start: "2026-04-10", timeline_end: "2026-04-12", actual_spent: 1500, payment_status: "Paid", payment_method: "Credit Card", payment_due: "2026-04-12", invoice_type: "tax_invoice_receipt", invoice_stage: "complete", invoice_status: "Received", notes: "", dealer_type: "osek_murshe" },
  ],
};

export const SAMPLE_COMMENTS = {
  "PRD26-06": [
    {
      id: "c-001",
      production_id: "PRD26-06",
      user_id: "u-001",
      author: "Omer Barak",
      avatar: null,
      body: "Script approved by creative. Shooting confirmed for March 8-10.",
      mentions: [],
      created_at: "2026-03-02T09:00:00.000Z",
    },
    {
      id: "c-002",
      production_id: "PRD26-06",
      user_id: "u-002",
      author: "Tomer Wilf Lezmy",
      avatar: null,
      body: "Budget has been approved. Let's move forward. @Omer Barak please confirm director availability.",
      mentions: ["Omer Barak"],
      created_at: "2026-03-03T11:30:00.000Z",
    },
  ],
};

export const SAMPLE_LINKS = {
  "PRD26-06": [
    { id: "l-001", production_id: "PRD26-06", category: "Scripts", title: "Final Script v3", url: "https://docs.google.com/document/d/example" },
    { id: "l-002", production_id: "PRD26-06", category: "Shooting", title: "Shooting Schedule", url: "https://docs.google.com/spreadsheets/d/example" },
    { id: "l-003", production_id: "PRD26-06", category: "Project Files", title: "Production Drive Folder", url: "https://drive.google.com/drive/folders/example" },
  ],
};

export const SAMPLE_CC_PURCHASES = [
  // PRD26-05 (Face Cream Direct)
  { id: "cc-001", production_id: "PRD26-05", store_name: "Diplomat", description: "Wardrobe accessories", amount_without_vat: 487.18, total_amount: 574, purchase_date: "2025-02-17T09:47:00", purchaser_name: "Omer Afriat", receipt_url: "", approval_status: "Approved", approved_by: "Omer Barak", parent_line_item_id: "", notes: "", submitted_at: "2025-02-17T09:47:00" },
  { id: "cc-002", production_id: "PRD26-05", store_name: "Fox", description: "Crew wardrobe", amount_without_vat: 203.26, total_amount: 239.85, purchase_date: "2025-02-17T11:31:00", purchaser_name: "Omer Afriat", receipt_url: "", approval_status: "Approved", approved_by: "Omer Barak", parent_line_item_id: "", notes: "", submitted_at: "2025-02-17T11:31:00" },
  { id: "cc-003", production_id: "PRD26-05", store_name: "Hoodies", description: "Talent wardrobe", amount_without_vat: 110.08, total_amount: 129.9, purchase_date: "2025-02-17T12:00:00", purchaser_name: "Omer Afriat", receipt_url: "", approval_status: "Approved", approved_by: "Omer Barak", parent_line_item_id: "", notes: "", submitted_at: "2025-02-17T12:00:00" },
  { id: "cc-004", production_id: "PRD26-05", store_name: "Mashbir", description: "Props purchase", amount_without_vat: 16.86, total_amount: 19.9, purchase_date: "2025-02-17T15:38:00", purchaser_name: "Omer Afriat", receipt_url: "", approval_status: "Approved", approved_by: "Omer Barak", parent_line_item_id: "", notes: "", submitted_at: "2025-02-17T15:38:00" },
  { id: "cc-005", production_id: "PRD26-05", store_name: "Stimatzki", description: "Office supplies", amount_without_vat: 14.41, total_amount: 17, purchase_date: "2025-02-17T15:30:00", purchaser_name: "Omer Afriat", receipt_url: "", approval_status: "Approved", approved_by: "Omer Barak", parent_line_item_id: "", notes: "", submitted_at: "2025-02-17T15:30:00" },
  { id: "cc-006", production_id: "PRD26-05", store_name: "Diplomat", description: "Wardrobe — hero outfit", amount_without_vat: 169.49, total_amount: 200, purchase_date: "2025-02-19T09:47:00", purchaser_name: "Omer Barak", receipt_url: "", approval_status: "Approved", approved_by: "Omer Barak", parent_line_item_id: "", notes: "", submitted_at: "2025-02-19T09:47:00" },
  // PRD26-06 (Sunscreen)
  { id: "cc-007", production_id: "PRD26-06", store_name: "הודיס בגדי ם", description: "Wardrobe for shoot", amount_without_vat: 254.24, total_amount: 300, purchase_date: "2025-03-16T15:59:00", purchaser_name: "Maya rapp", receipt_url: "", approval_status: "Approved", approved_by: "Omer Barak", parent_line_item_id: "", notes: "", submitted_at: "2025-03-16T15:59:00" },
  { id: "cc-008", production_id: "PRD26-06", store_name: "Top ten", description: "Talent wardrobe", amount_without_vat: 164, total_amount: 200, purchase_date: "2025-03-16T16:42:00", purchaser_name: "Maya rapp", receipt_url: "", approval_status: "Approved", approved_by: "Omer Barak", parent_line_item_id: "", notes: "", submitted_at: "2025-03-16T16:42:00" },
  { id: "cc-009", production_id: "PRD26-06", store_name: "רונזר", description: "Equipment rental misc", amount_without_vat: 304.92, total_amount: 359.8, purchase_date: "2025-03-16T18:02:00", purchaser_name: "Maya rapp", receipt_url: "", approval_status: "Pending", approved_by: "", parent_line_item_id: "", notes: "", submitted_at: "2025-03-16T18:02:00" },
  { id: "cc-010", production_id: "PRD26-06", store_name: "Super Pharm", description: "Skincare props", amount_without_vat: 114.15, total_amount: 134.7, purchase_date: "2025-03-17T09:16:00", purchaser_name: "Omer Afriat", receipt_url: "", approval_status: "Pending", approved_by: "", parent_line_item_id: "", notes: "", submitted_at: "2025-03-17T09:16:00" },
];

export const SAMPLE_CASTING = [
  // PRD26-06 (Invisible Sunscreen)
  { id: "cast-001", production_id: "PRD26-06", project_name: "Sunscreen", brand_id: "particle", name: "Savanna Chilchik", photo_url: "", role: "Actor", period: "Perpetually", start_date: "2025-04-01", end_date: "", contract_status: "Running", usage: ["Digital"], signed_contract_url: "", contract_manager_name: "Maya rapp", notes: "No agency", created_at: "2025-04-01T00:00:00" },
  { id: "cast-002", production_id: "PRD26-06", project_name: "Sunscreen", brand_id: "particle", name: "Maya Meents", photo_url: "", role: "Actor", period: "1 Year", start_date: "2025-04-28", end_date: "2026-04-28", contract_status: "Running", usage: ["Digital", "TV"], signed_contract_url: "", contract_manager_name: "Yuli Group", notes: "", created_at: "2025-04-28T00:00:00" },
  { id: "cast-003", production_id: "PRD26-06", project_name: "Sunscreen", brand_id: "particle", name: "Brian Unger", photo_url: "", role: "Actor", period: "1 Year", start_date: "2025-04-28", end_date: "2026-04-29", contract_status: "Running", usage: ["Stills", "Digital", "TV"], signed_contract_url: "", contract_manager_name: "HH", notes: "75% fr", created_at: "2025-04-28T00:00:00" },
  { id: "cast-004", production_id: "PRD26-06", project_name: "Sunscreen", brand_id: "particle", name: "Michael Harpaz - Sunscreen + Their Face", photo_url: "", role: "Actor", period: "1 Year", start_date: "2025-04-28", end_date: "2026-04-28", contract_status: "Running", usage: ["TV", "Digital", "Stills"], signed_contract_url: "", contract_manager_name: "HH", notes: "75% fr", created_at: "2025-04-28T00:00:00" },
  { id: "cast-005", production_id: "PRD26-06", project_name: "Sunscreen", brand_id: "particle", name: "Albert Amergi", photo_url: "", role: "Extra", period: "Perpetually", start_date: "2025-05-19", end_date: "", contract_status: "Running", usage: ["TV", "Digital", "Stills"], signed_contract_url: "", contract_manager_name: "", notes: "", created_at: "2025-05-19T00:00:00" },
  { id: "cast-006", production_id: "PRD26-06", project_name: "Sunscreen", brand_id: "particle", name: "Stanely", photo_url: "", role: "Extra", period: "Perpetually", start_date: "2025-05-19", end_date: "", contract_status: "Running", usage: ["TV", "Digital", "Stills"], signed_contract_url: "", contract_manager_name: "", notes: "", created_at: "2025-05-19T00:00:00" },
  { id: "cast-007", production_id: "PRD26-06", project_name: "Sunscreen", brand_id: "particle", name: "Matan Carmel + 6 extras", photo_url: "", role: "Extra", period: "Perpetually", start_date: "2025-04-28", end_date: "", contract_status: "Running", usage: ["TV", "Digital"], signed_contract_url: "", contract_manager_name: "", notes: "", created_at: "2025-04-28T00:00:00" },
  // PRD26-05 (Face Cream Direct)
  { id: "cast-008", production_id: "PRD26-05", project_name: "Face Cream Direct", brand_id: "particle", name: "Maor Bubil", photo_url: "", role: "Model", period: "Perpetually", start_date: "2024-11-04", end_date: "", contract_status: "Running", usage: ["Any Use"], signed_contract_url: "", contract_manager_name: "Sharon Agency", notes: "", created_at: "2024-11-04T00:00:00" },
  { id: "cast-009", production_id: "PRD26-05", project_name: "Face Cream Direct", brand_id: "particle", name: "Assaf Goldstien", photo_url: "", role: "Model", period: "Perpetually", start_date: "2024-11-04", end_date: "", contract_status: "Running", usage: ["Any Use"], signed_contract_url: "", contract_manager_name: "", notes: "", created_at: "2024-11-04T00:00:00" },
  { id: "cast-010", production_id: "PRD26-05", project_name: "Face Cream Direct", brand_id: "particle", name: "Nissim Krispin", photo_url: "", role: "Model", period: "Perpetually", start_date: "2024-11-04", end_date: "", contract_status: "Running", usage: ["Any Use"], signed_contract_url: "", contract_manager_name: "", notes: "", created_at: "2024-11-04T00:00:00" },
  { id: "cast-011", production_id: "PRD26-05", project_name: "Face Cream Direct", brand_id: "particle", name: "Smith Kaan", photo_url: "", role: "Model", period: "Perpetually", start_date: "2024-07-14", end_date: "", contract_status: "Running", usage: ["Any Use"], signed_contract_url: "", contract_manager_name: "", notes: "", created_at: "2024-07-14T00:00:00" },
];

export const SAMPLE_USERS = [
  { id: "u-001", email: "omer@particleformen.com",     name: "Omer Barak",       role: "Admin",  brand: "particle", brand_ids: ["particle", "blurr"], active: true, super_admin: true  },
  { id: "u-002", email: "tomer@particleformen.com",    name: "Tomer Wilf Lezmy", role: "Admin",  brand: "particle", brand_ids: ["particle", "blurr"], active: true, super_admin: false },
  { id: "u-003", email: "producer@particleformen.com", name: "Dana Levy",        role: "Editor", brand: "particle", brand_ids: ["particle"],           active: true, super_admin: false },
  { id: "u-004", email: "viewer@particleformen.com",   name: "Roy Mizrahi",      role: "Viewer", brand: "particle", brand_ids: ["particle"],           active: true, super_admin: false },
];

export const PRODUCT_TYPES = [
  "Face Cream", "Sunscreen", "Gravité", "Neoroot", "Hand Cream",
  "Anti-Gray Serum", "Shaving Gel", "Brandformance", "Eye Cream",
  "Body Wash", "Other",
];

export const STAGES = ["Pre Production", "Production", "Post", "Paused", "Pending", "Completed"];

export const PRODUCTION_TYPES = ["Remote Shoot", "Shoot", "AI"];

export const LINE_ITEM_TYPES = ["Crew", "Equipment", "Catering & Transport", "Post", "Office"];

export const LINE_ITEM_STATUSES = ["Working on it", "Done", "Stuck", "Not Started"];

export const PAYMENT_METHODS = ["Bank Transfer", "Credit Card", "PayPal", "Remote", "Office Card"];

export const BUSINESS_TYPES = ["Company (בע\"מ)", "Self-Employed (ע.מ)", "Individual", "Agency"];

export const EXPENSE_CATEGORIES = [
  "Director", "Talent", "AI Tools", "Sound", "Post Production",
  "Offline Editor", "Rights Renewal", "Other",
];
